### ISSUE TITLE
File not found error for service account key  json file

### ISSUE THREAD

**Issue by srjmnh** [turhancan97/Intelligent-Face-Recognition-Attendance-System#2]
I have configured the database.yaml with all the firebase info, and gave the path of my service account key file on it as well. 
But upon running the program I am getting the following file not found error, although I have verified the path is correct and file exist on it. 
Please find the error below 

I have downloaded the file and renamed it as serviceAccountKey.json

<img width="1213" alt="Screenshot 2024-03-31 at 12 56 42" src="https://github.com/turhancan97/Intelligent-Face-Recognition-Attendance-System/assets/30594403/8c5d4157-3b00-426c-bc97-526314363cdb">

My database.yaml file is configured as below,
<img width="970" alt="Screenshot 2024-03-31 at 12 58 06" src="https://github.com/turhancan97/Intelligent-Face-Recognition-Attendance-System/assets/30594403/feb75c31-65b6-433f-9cb5-14b502d83082">

**Comment by srjmnh** [comment]
I have renamed the file as serviceAccountKey.json

**Comment by turhancan97** [comment]
I think your problem is that you are not deleting the '<>' characters from the default configuration file. You should define it as follows for it to work properly:

<img width="671" alt="image" src="https://github.com/turhancan97/Intelligent-Face-Recognition-Attendance-System/assets/22428774/420b6473-e52e-4d79-9f53-ae0a3d86e290">

**Comment by srjmnh** [comment]
How silly of me, corrected this and the application now works perfect, looking forward to testing this and learning so much from your repo. 
You are doing great work, huge thanks to you for everything.
